repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=120"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.249
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports", "--recursive", "--exclude", "venv,t_api.py"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
